# Generated by Django 4.1.4 on 2022-12-18 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oilasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(choices=[('Hayvonlar', 'Hayvonlar'), ("O'simliklar", "O'simliklar")], default='Hayvonlar', max_length=11)),
                ('nomi', models.CharField(max_length=255)),
                ('muallifi', models.CharField(max_length=255)),
                ('yili', models.IntegerField(default=2000)),
                ('maqomi', models.TextField()),
                ('tarqalishi', models.TextField()),
                ('yashash_joylari', models.TextField()),
                ('soni', models.TextField()),
                ('yashash_tarzi', models.TextField()),
                ('cheklovchi_omillar', models.TextField()),
                ('kupaytirish', models.CharField(max_length=255)),
                ('choralari', models.TextField()),
                ('img', models.ImageField(default='', upload_to='')),
                ('oilasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redmap.oilasi')),
            ],
            options={
                'verbose_name': 'Tur',
                'verbose_name_plural': 'Turlari',
            },
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redmap.nature')),
            ],
            options={
                'verbose_name': 'Kordinata',
                'verbose_name_plural': 'Kordinatalar',
            },
        ),
    ]
