# Generated by Django 4.1.4 on 2022-12-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redmap', '0002_alter_oilasi_options_remove_nature_muallifi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='region',
            field=models.CharField(choices=[['Xorazm', 'Xorazm'], ['Andijan', 'Andijon'], ['Surxondaryo', 'Surxondaryo'], ['Buxoro', 'Buxoro'], ['Toshkent', 'Toshkent'], ['Navoiy', 'Navoiy'], ['Fargona', "Farg'ona"], ['Nukus', 'Nukus'], ['Jizzax', 'Jizzax'], ['Qarshi', 'Qarshi'], ['Namangan', 'Namangan'], ['Samarkand', 'Samarkand'], ['Sirdaryo', 'Sirdaryo']], max_length=20),
        ),
    ]
